/*
 * Decompiled with CFR 0.152.
 */
package com.seedfinding.latticg.generator;

import com.seedfinding.latticg.JavaRandomReverser;
import com.seedfinding.latticg.RandomReverser;
import com.seedfinding.latticg.math.component.BigMatrix;
import com.seedfinding.latticg.math.component.BigMatrixUtil;
import com.seedfinding.latticg.math.component.BigVector;
import com.seedfinding.latticg.math.lattice.enumerate.EnumerateRt;
import com.seedfinding.latticg.math.optimize.Optimize;
import com.seedfinding.latticg.reversal.Program;
import com.seedfinding.latticg.reversal.calltype.CallType;
import com.seedfinding.latticg.reversal.calltype.java.*;
import com.seedfinding.latticg.util.DeserializeRt;
import com.seedfinding.latticg.util.Mth;

import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.LongStream;

public final class ClassGenerator {
    private static final String TAB = "    ";
    private static final String TAB2 = "        ";
    private static final String TAB3 = "            ";
    private String fileHeader = "";
    private final String packageName;
    private final String className;
    private final Program program;
    private final StringBuilder classBody = new StringBuilder();
    private final StringBuilder parameters = new StringBuilder();
    private final StringBuilder boundsConfig = new StringBuilder();
    private final Set<String> imports = new TreeSet<String>();
    private int latticeIndex = 0;

    public ClassGenerator(String packageName, String className, Program program) {
        this.packageName = packageName;
        this.className = className;
        this.program = program;
    }

    public ClassGenerator withFileHeader(String fileHeader) {
        this.fileHeader = fileHeader;
        return this;
    }

    public String generate() {
        this.classBody.setLength(0);
        this.parameters.setLength(0);
        this.boundsConfig.setLength(0);
        this.imports.clear();
        this.latticeIndex = 0;
        this.classBody.append("public final class ").append(this.className).append(" {\n");
        this.classBody.append("    private ").append(this.className).append("() {}\n");
        this.generateBody();
        this.classBody.append("}\n");
        StringBuilder result = new StringBuilder();
        if (!this.fileHeader.isEmpty()) {
            result.append(this.fileHeader).append("\n\n");
        }
        result.append("package ").append(this.packageName).append(";\n\n");
        if (!this.imports.isEmpty()) {
            result.append(this.imports.stream().map(i -> "import " + i + ";").collect(Collectors.joining("\n"))).append("\n\n");
        }
        result.append("// CLASS GENERATED BY LATTICG, DO NOT EDIT MANUALLY\n");
        result.append((CharSequence)this.classBody);
        return result.toString();
    }

    private void generateBody() {
        if (!this.program.getFilteredSkips().isEmpty()) {
            throw new IllegalStateException("ClassGenerator does not support filtered skips");
        }
        JavaRandomReverser reverser = new JavaRandomReverser(Collections.emptyList());
        List<CallType<?>> calls = this.program.getCalls();
        List<Long> skips = this.program.getSkips();
        for (int i = 0; i < calls.size(); ++i) {
            CallType<?> call = calls.get(i);
            reverser.addUnmeasuredSeeds(skips.get(i));
            if (call instanceof NextBooleanCall) {
                reverser.addNextBooleanCall(false);
                continue;
            }
            if (call instanceof NextDoubleCall) {
                reverser.addNextDoubleCall(0.0, 0.0, true, true);
                continue;
            }
            if (call instanceof NextFloatCall) {
                reverser.addNextFloatCall(0.0f, 0.0f, true, true);
                continue;
            }
            if (call instanceof NextIntCall) {
                reverser.addNextIntCall(((NextIntCall)call).getBound(), 0, 0);
                continue;
            }
            if (call instanceof UnboundedNextIntCall) {
                reverser.addNextIntCall(0, 0);
                continue;
            }
            if (call instanceof NextLongCall) {
                reverser.addNextLongCall(0L, 0L);
                continue;
            }
            if (call instanceof NextFloatCall.FloatRange) {
                reverser.addNextFloatCall(0.0f, 0.5f);
                continue;
            }
            if (call instanceof NextIntCall.IntRange) {
                int bound = ((NextIntCall.IntRange)call).getBound();
                reverser.addNextIntCall(bound, 0, bound / 2);
                continue;
            }
            if (call instanceof UnboundedNextIntCall.IntRange) {
                reverser.addNextIntCall(0, 0x7FFFFFFE);
                continue;
            }
            if (call instanceof NextDoubleCall.DoubleRange) {
                reverser.addNextDoubleCall(0.0, 0.5);
                continue;
            }
            if (call instanceof NextLongCall.LongRange) {
                reverser.addNextLongCall(0L, Long.MAX_VALUE);
                continue;
            }
            if (call instanceof NextFloatCall.Ranged) {
                reverser.addNextFloatCall(0.0f, Mth.clamp(((NextFloatCall.Ranged)call).getExpectedSize(), 0.0f, 1.0f));
                continue;
            }
            if (call instanceof NextIntCall.Ranged) {
                NextIntCall.Ranged rangedCall = (NextIntCall.Ranged)call;
                reverser.addNextIntCall(rangedCall.getBound(), 0, Mth.clamp(rangedCall.getExpectedSize(), 0, rangedCall.getBound() - 1));
                continue;
            }
            if (call instanceof UnboundedNextIntCall.Ranged) {
                reverser.addNextIntCall(0, ((UnboundedNextIntCall.Ranged)call).getExpectedSize());
                continue;
            }
            if (call instanceof NextDoubleCall.Ranged) {
                reverser.addNextDoubleCall(0.0, Mth.clamp(((NextDoubleCall.Ranged)call).getExpectedSize(), 1.4901161193847656E-8, 1.0));
                continue;
            }
            if (call instanceof NextLongCall.Ranged) {
                reverser.addNextLongCall(0L, Math.max(((NextLongCall.Ranged)call).getExpectedSize(), 0x100000000L));
                continue;
            }
            throw new IllegalStateException("ClassGenerator does not support " + call.getClass().getSimpleName() + " call type");
        }
        RandomReverser.GenerationInfo generationInfo = reverser.createGenerationInfo();
        this.classBody.append("    private static final ");
        this.appendClassName(this.classBody, BigMatrix.class);
        this.classBody.append(" BASIS = ");
        this.appendClassName(this.classBody, DeserializeRt.class);
        this.classBody.append(".mat(\n");
        this.classBody.append(SerializeUtil.matrixToStringLiteral(TAB2, generationInfo.basis)).append(");\n");
        BigMatrix rootInverse = BigMatrixUtil.inverse(generationInfo.basis);
        this.classBody.append("    private static final ");
        this.appendClassName(this.classBody, BigMatrix.class);
        this.classBody.append(" ROOT_INV = ");
        this.appendClassName(this.classBody, DeserializeRt.class);
        this.classBody.append(".mat(\n");
        this.classBody.append(SerializeUtil.matrixToStringLiteral(TAB2, rootInverse)).append(");\n");
        this.classBody.append("    private static final ");
        this.appendClassName(this.classBody, BigVector.class);
        this.classBody.append(" ORIGIN = ");
        this.appendClassName(this.classBody, DeserializeRt.class);
        this.classBody.append(".vec(\n");
        this.classBody.append(SerializeUtil.vectorToStringLiteral(TAB2, generationInfo.offset)).append(");\n");
        this.classBody.append("    private static final ");
        this.appendClassName(this.classBody, BigVector.class);
        this.classBody.append(" ROOT_ORIGIN = ");
        this.appendClassName(this.classBody, DeserializeRt.class);
        this.classBody.append(".vec(\n");
        this.classBody.append(SerializeUtil.vectorToStringLiteral(TAB2, rootInverse.multiply(generationInfo.offset))).append(");\n\n");
        this.classBody.append("    /**\n");
        this.classBody.append("     * Finds all values of {@code seed} that could produce the given results in the following code:\n");
        this.classBody.append("     * <pre>{@code\n");
        this.classBody.append("     *    Random rand = new Random(seed ^ 0x5DEECE66DL);\n");
        int nextBooleans = 0;
        int nextDoubles = 0;
        int nextFloats = 0;
        int nextInts = 0;
        int nextLongs = 0;
        for (int i = 0; i < calls.size(); ++i) {
            String varName;
            long skipsHere = skips.get(i);
            if (skipsHere != 0L) {
                if (skipsHere > 0L) {
                    this.classBody.append("     *    // Skip ").append(skipsHere).append(" random call");
                } else {
                    this.classBody.append("     *    // Go backwards by ").append(-skipsHere).append(" random call");
                }
                if (Math.abs(skipsHere) != 1L) {
                    this.classBody.append('s');
                }
                this.classBody.append('\n');
            }
            CallType<?> call = calls.get(i);
            if (this.parameters.length() != 0) {
                this.parameters.append(", ");
            }
            if (call instanceof NextBooleanCall) {
                varName = "nextBoolean" + ++nextBooleans;
                this.nextBooleanCall((NextBooleanCall)call, varName);
                continue;
            }
            if (call instanceof NextDoubleCall) {
                varName = "nextDouble" + ++nextDoubles;
                this.nextDoubleCall(varName, nextDoubles);
                continue;
            }
            if (call instanceof NextFloatCall) {
                varName = "nextFloat" + ++nextFloats;
                this.nextFloatCall(varName, nextFloats);
                continue;
            }
            if (call instanceof NextIntCall) {
                varName = "nextInt" + ++nextInts;
                this.nextIntCall((NextIntCall)call, varName);
                continue;
            }
            if (call instanceof UnboundedNextIntCall) {
                varName = "nextInt" + ++nextInts;
                this.unboundedNextIntCall(varName);
                continue;
            }
            if (call instanceof NextLongCall) {
                varName = "nextLong" + ++nextLongs;
                this.nextLongCall(varName, nextLongs);
                continue;
            }
            if (call instanceof NextFloatCall.FloatRange) {
                varName = "nextFloat" + ++nextFloats;
                this.floatRangeCall((NextFloatCall.FloatRange)call, varName);
                continue;
            }
            if (call instanceof NextIntCall.IntRange) {
                varName = "nextInt" + ++nextInts;
                this.intRangeCall((NextIntCall.IntRange)call, varName);
                continue;
            }
            if (call instanceof UnboundedNextIntCall.IntRange) {
                varName = "nextInt" + ++nextInts;
                this.unboundedIntRangeCall((UnboundedNextIntCall.IntRange)call, varName);
                continue;
            }
            if (call instanceof NextDoubleCall.DoubleRange) {
                varName = "nextDouble" + ++nextDoubles;
                this.doubleRangeCall((NextDoubleCall.DoubleRange)call, varName);
                continue;
            }
            if (call instanceof NextLongCall.LongRange) {
                varName = "nextLong" + ++nextLongs;
                this.longRangeCall((NextLongCall.LongRange)call, varName);
                continue;
            }
            if (call instanceof NextFloatCall.Ranged) {
                this.floatRangedCall("minNextFloat" + ++nextFloats, "maxNextFloat" + nextFloats, nextFloats);
                continue;
            }
            if (call instanceof NextIntCall.Ranged) {
                this.intRangedCall((NextIntCall.Ranged)call, "minNextInt" + ++nextInts, "maxNextInt" + nextInts, nextInts);
                continue;
            }
            if (call instanceof UnboundedNextIntCall.Ranged) {
                this.unboundedIntRangedCall("minNextInt" + ++nextInts, "maxNextInt" + nextInts, nextInts);
                continue;
            }
            if (call instanceof NextDoubleCall.Ranged) {
                this.doubleRangedCall("minNextDouble" + ++nextDoubles, "maxNextDoubles" + nextDoubles, nextDoubles);
                continue;
            }
            if (call instanceof NextLongCall.Ranged) {
                this.longRangedCall("minNextLong" + ++nextLongs, "maxNextLongs" + nextLongs, nextLongs);
                continue;
            }
            throw new AssertionError((Object)"Unknown call type should have been caught in previous loop");
        }
        if (this.latticeIndex != generationInfo.dimensions) {
            throw new AssertionError((Object)"Not all dimensions in the lattice have been accounted for");
        }
        this.classBody.append("     * }</pre>\n");
        this.classBody.append("     *\n");
        this.classBody.append(String.format("     * <p>This code skips %f%% of seeds in its search.\n", (1.0 - generationInfo.successChance) * 100.0));
        this.classBody.append("     */\n");
        this.classBody.append("    public static ");
        this.appendClassName(this.classBody, LongStream.class);
        this.classBody.append(" getSeeds(").append((CharSequence)this.parameters).append(") {\n");
        this.classBody.append(TAB2);
        this.appendClassName(this.classBody, Optimize.Builder.class);
        this.classBody.append(" builder = ");
        this.appendClassName(this.classBody, Optimize.Builder.class);
        this.classBody.append(".ofSize(").append(generationInfo.dimensions).append(");\n");
        this.classBody.append((CharSequence)this.boundsConfig);
        this.classBody.append("        return ");
        this.appendClassName(this.classBody, EnumerateRt.class);
        this.classBody.append(".enumerate(BASIS, ORIGIN, builder.build(), ROOT_INV, ROOT_ORIGIN)\n");
        this.classBody.append(String.format("            .mapToLong(vec -> (vec.get(0).getNumerator().longValue() * 0x%xL + 0x%xL) & ((1L << 48) - 1));\n", generationInfo.r.multiplier, generationInfo.r.addend));
        this.classBody.append("    }\n");
    }

    private void nextBooleanCall(NextBooleanCall call, String varName) {
        this.classBody.append("     *    boolean ").append(varName).append(" = ");
        if (call.isInverted()) {
            this.classBody.append('!');
        }
        this.classBody.append("rand.nextBoolean();\n");
        this.parameters.append("boolean ").append(varName);
        this.boundsConfig.append(String.format("        if (%s) {\n", varName));
        this.boundsConfig.append(String.format("            builder.withLowerBound(%d, %s).withUpperBound(%d, %s);\n", this.latticeIndex, call.isInverted() ? "0" : "1L << 47", this.latticeIndex, call.isInverted() ? "(1L << 47) - 1" : "(1L << 48) - 1"));
        this.boundsConfig.append("        } else {\n");
        this.boundsConfig.append(String.format("            builder.withLowerBound(%d, %s).withUpperBound(%d, %s);\n", this.latticeIndex, call.isInverted() ? "1L << 47" : "0", this.latticeIndex, call.isInverted() ? "(1L << 48) - 1" : "(1L << 47) - 1"));
        this.boundsConfig.append("        }\n");
        ++this.latticeIndex;
    }

    private void nextDoubleCall(String varName, int nextDoubles) {
        this.classBody.append("     *    double ").append(varName).append(" = rand.nextDouble();\n");
        this.parameters.append("double ").append(varName);
        String longVar = "longDouble" + nextDoubles;
        this.boundsConfig.append(String.format("        long %s = (long) (%s * 0x1.0p53);\n", longVar, varName));
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, %s >> 27 << 22).withUpperBound(%d, (%s >> 27 << 22) | 0x3fffff);\n", this.latticeIndex, longVar, this.latticeIndex, longVar));
        ++this.latticeIndex;
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (%s & 0x7ffffff) << 21).withUpperBound(%d, ((%s & 0x7ffffff) << 21) | 0x1fffff);\n", this.latticeIndex, longVar, this.latticeIndex, longVar));
        ++this.latticeIndex;
    }

    private void nextFloatCall(String varName, int nextFloats) {
        this.classBody.append("     *    float ").append(varName).append(" = rand.nextFloat();\n");
        this.parameters.append("float ").append(varName);
        String longVar = "longFloat" + nextFloats;
        this.boundsConfig.append(String.format("        long %s = (long) (%s * 0x1.0p24F);\n", longVar, varName));
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, %s << 24).withUpperBound(%d, (%s << 24) | 0xffffff);\n", this.latticeIndex, longVar, this.latticeIndex, longVar));
        ++this.latticeIndex;
    }

    private void nextIntCall(NextIntCall call, String varName) {
        this.classBody.append("     *    int ").append(varName).append(" = rand.nextInt(").append(call.getBound()).append(");\n");
        this.parameters.append("int ").append(varName);
        if ((call.getBound() & -call.getBound()) == call.getBound()) {
            int log = Integer.numberOfTrailingZeros(call.getBound());
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) %s << %d).withUpperBound(%d, ((long) (%s + 1) << %d) - 1);\n", this.latticeIndex, varName, 48 - log, this.latticeIndex, varName, 48 - log));
            ++this.latticeIndex;
        } else {
            long residue = 0x1000000000000L % ((long)call.getBound() << 17);
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, 0).withUpperBound(%d, (1L << 48) - %dL);\n", this.latticeIndex, this.latticeIndex, residue));
            ++this.latticeIndex;
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) %s << 17).withUpperBound(%d, ((long) %s << 17) | 0x1ffff);\n", this.latticeIndex, varName, this.latticeIndex, varName));
            ++this.latticeIndex;
        }
    }

    private void unboundedNextIntCall(String varName) {
        this.classBody.append("     *    int ").append(varName).append(" = rand.nextInt();\n");
        this.parameters.append("int ").append(varName);
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) %s << 16).withUpperBound(%d, ((long) (%s + 1) << 16) - 1);\n", this.latticeIndex, varName, this.latticeIndex, varName));
        ++this.latticeIndex;
    }

    private void nextLongCall(String varName, int nextLongs) {
        this.classBody.append("     *    long ").append(varName).append(" = rand.nextLong();\n");
        this.parameters.append("long ").append(varName);
        String firstSeedName = "longFirstSeed" + nextLongs;
        this.boundsConfig.append(String.format("        long %s = %s >>> 32 << 16;\n", firstSeedName, varName));
        this.boundsConfig.append(String.format("        if (%s < 0) {\n", varName));
        this.boundsConfig.append(String.format("            %s += (1L << 16);\n", firstSeedName));
        this.boundsConfig.append("        }\n");
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, %s).withUpperBound(%d, %s + (1L << 16) - 1);\n", this.latticeIndex, firstSeedName, this.latticeIndex, firstSeedName));
        ++this.latticeIndex;
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (%s & 0xffffffffL) << 16).withUpperBound(%d, (((%s & 0xffffffffL) + 1) << 16) - 1);\n", this.latticeIndex, varName, this.latticeIndex, varName));
        ++this.latticeIndex;
    }

    private void floatRangeCall(NextFloatCall.FloatRange call, String varName) {
        boolean hasUpperBound;
        boolean hasLowerBound = ((Float)call.getMin()).floatValue() != 0.0f || call.isMinStrict();
        boolean bl = hasUpperBound = ((Float)call.getMax()).floatValue() != 1.0f || !call.isMaxStrict();
        if (hasLowerBound && hasUpperBound) {
            throw new IllegalStateException("ClassGenerator does not support nextFloat with two bounds");
        }
        if (hasLowerBound) {
            Object[] objectArray = new Object[3];
            objectArray[0] = varName;
            objectArray[1] = call.isMinStrict() ? (call.isInverted() ? "<=" : ">") : (call.isInverted() ? "<" : ">=");
            objectArray[2] = call.getMin();
            this.classBody.append(String.format("     *    boolean %s = rand.nextFloat() %s %fF;\n", objectArray));
        } else if (hasUpperBound) {
            Object[] objectArray = new Object[3];
            objectArray[0] = varName;
            objectArray[1] = call.isMaxStrict() ? (call.isInverted() ? ">=" : "<") : (call.isInverted() ? ">" : "<=");
            objectArray[2] = call.getMax();
            this.classBody.append(String.format("     *    boolean %s = rand.nextFloat() %s %fF;\n", objectArray));
        } else {
            this.classBody.append("     *    rand.nextFloat();\n");
            this.classBody.append(String.format("     *    boolean %s = %s;\n", varName, !call.isInverted()));
        }
        this.parameters.append("boolean ").append(varName);
        if (hasLowerBound || hasUpperBound) {
            this.boundsConfig.append(String.format("        if (%s) {\n", varName));
            String ifTrue = String.format("            builder.withLowerBound(%d, %s(long) (%fF * 0x1.0p24F)%s << 24).withUpperBound(%d, (%s(long) (%fF * 0x1.0p24F)%s << 24) - 1);\n", this.latticeIndex, call.isMinStrict() ? "(" : "", call.getMin(), call.isMinStrict() ? " + 1)" : "", this.latticeIndex, !call.isMaxStrict() ? "(" : "", call.getMax(), !call.isMaxStrict() ? " + 1)" : "");
            String ifFalse = hasLowerBound ? String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%s(long) (%fF * 0x1.0p24F)%s << 24) - 1);\n", this.latticeIndex, this.latticeIndex, call.isMinStrict() ? "(" : "", call.getMin(), call.isMinStrict() ? " + 1)" : "") : String.format("            builder.withLowerBound(%d, %s(long) (%fF * 0x1.0p24F)%s << 24).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, !call.isMaxStrict() ? "(" : "", call.getMax(), !call.isMaxStrict() ? " + 1)" : "", this.latticeIndex);
            this.boundsConfig.append(call.isInverted() ? ifFalse : ifTrue);
            this.boundsConfig.append("        } else {\n");
            this.boundsConfig.append(call.isInverted() ? ifTrue : ifFalse);
            this.boundsConfig.append("        }\n");
        } else {
            this.boundsConfig.append("        if (");
            if (!call.isInverted()) {
                this.boundsConfig.append('!');
            }
            this.boundsConfig.append(varName).append(") {\n");
            this.boundsConfig.append("            return ");
            this.appendClassName(this.boundsConfig, LongStream.class);
            this.boundsConfig.append(".empty();\n");
            this.boundsConfig.append("        }\n");
        }
        ++this.latticeIndex;
    }

    private void intRangeCall(NextIntCall.IntRange call, String varName) {
        int min = (Integer)call.getMin();
        int max = (Integer)call.getMax();
        if (call.isMinStrict()) {
            ++min;
        }
        if (call.isMaxStrict()) {
            --max;
        }
        if (min > 0 && max < call.getBound() - 1) {
            throw new IllegalStateException("ClassGenerator does not support nextInt with two bounds");
        }
        if (min <= 0 && max >= call.getBound() - 1) {
            this.classBody.append("     *    rand.nextInt(").append(call.getBound()).append(");\n");
            this.classBody.append("     *    boolean ").append(varName).append(" = true;\n");
            this.parameters.append("boolean ").append(varName);
            this.boundsConfig.append("        if (");
            if (!call.isInverted()) {
                this.boundsConfig.append('!');
            }
            this.boundsConfig.append(varName).append(") {\n");
            this.boundsConfig.append("            return ");
            this.appendClassName(this.boundsConfig, LongStream.class);
            this.boundsConfig.append(".empty();\n");
            this.boundsConfig.append("        }\n");
            ++this.latticeIndex;
            return;
        }
        Object[] objectArray = new Object[4];
        objectArray[0] = varName;
        objectArray[1] = call.getBound();
        objectArray[2] = min > 0 ? (call.isMinStrict() ? (call.isInverted() ? "<=" : ">") : (call.isInverted() ? "<" : ">=")) : (call.isMaxStrict() ? (call.isInverted() ? ">=" : "<") : (call.isInverted() ? ">" : "<="));
        objectArray[3] = min > 0 ? (Integer)call.getMin() : (Integer)call.getMax();
        this.classBody.append(String.format("     *    boolean %s = rand.nextInt(%d) %s %d;\n", objectArray));
        this.parameters.append("boolean ").append(varName);
        if ((call.getBound() & -call.getBound()) == call.getBound()) {
            String ifFalse;
            String ifTrue;
            int log = Integer.numberOfTrailingZeros(call.getBound());
            if (min > 0) {
                ifTrue = String.format("            builder.withLowerBound(%d, %dL << %d).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, min, 48 - log, this.latticeIndex);
                ifFalse = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%dL << %d) - 1);\n", this.latticeIndex, this.latticeIndex, min, 48 - log);
            } else {
                ifTrue = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%dL << %d) - 1);\n", this.latticeIndex, this.latticeIndex, max + 1, 48 - log);
                ifFalse = String.format("            builder.withLowerBound(%d, %dL << %d).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, max + 1, 48 - log, this.latticeIndex);
            }
            this.boundsConfig.append(String.format("        if(%s) {\n", varName));
            this.boundsConfig.append(call.isInverted() ? ifFalse : ifTrue);
            this.boundsConfig.append("        } else {\n");
            this.boundsConfig.append(call.isInverted() ? ifTrue : ifFalse);
            this.boundsConfig.append("        }\n");
            ++this.latticeIndex;
        } else {
            String ifFalse;
            String ifTrue;
            long residue = 0x1000000000000L % ((long)call.getBound() << 17);
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, 0).withUpperBound(%d, (1L << 48) - %d);\n", this.latticeIndex, this.latticeIndex, residue));
            ++this.latticeIndex;
            if (min > 0) {
                ifTrue = String.format("            builder.withLowerBound(%d, %dL << 17).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, min, this.latticeIndex);
                ifFalse = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%dL << 17) - 1);\n", this.latticeIndex, this.latticeIndex, min);
            } else {
                ifTrue = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%dL << 17) - 1);\n", this.latticeIndex, this.latticeIndex, max + 1);
                ifFalse = String.format("            builder.withLowerBound(%d, %dL << 17).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, max + 1, this.latticeIndex);
            }
            this.boundsConfig.append(String.format("        if (%s) {\n", varName));
            this.boundsConfig.append(call.isInverted() ? ifFalse : ifTrue);
            this.boundsConfig.append("        } else {\n");
            this.boundsConfig.append(call.isInverted() ? ifTrue : ifFalse);
            this.boundsConfig.append("        }\n");
            ++this.latticeIndex;
        }
    }

    private void unboundedIntRangeCall(UnboundedNextIntCall.IntRange call, String varName) {
        throw new IllegalStateException("ClassGenerator does not support unbounded nextInt() ranges");
    }

    private void doubleRangeCall(NextDoubleCall.DoubleRange call, String varName) {
        boolean hasUpperBound;
        boolean hasLowerBound = (Double)call.getMin() != 0.0 || call.isMinStrict();
        boolean bl = hasUpperBound = (Double)call.getMax() != 1.0 || !call.isMaxStrict();
        if (hasLowerBound && hasUpperBound) {
            throw new IllegalStateException("ClassGenerator does not support nextDouble with two bounds");
        }
        if (hasLowerBound) {
            Object[] objectArray = new Object[3];
            objectArray[0] = varName;
            objectArray[1] = call.isMinStrict() ? (call.isInverted() ? "<=" : ">") : (call.isInverted() ? "<" : ">=");
            objectArray[2] = call.getMin();
            this.classBody.append(String.format("     *    boolean %s = rand.nextDouble() %s %f;\n", objectArray));
        } else if (hasUpperBound) {
            Object[] objectArray = new Object[3];
            objectArray[0] = varName;
            objectArray[1] = call.isMaxStrict() ? (call.isInverted() ? ">=" : "<") : (call.isInverted() ? ">" : "<=");
            objectArray[2] = call.getMax();
            this.classBody.append(String.format("     *    boolean %s = rand.nextDouble() %s %f;\n", objectArray));
        } else {
            this.classBody.append("     *    rand.nextDouble();\n");
            this.classBody.append(String.format("     *    boolean %s = %s;\n", varName, !call.isInverted()));
        }
        this.parameters.append("boolean ").append(varName);
        long minLong = (long)((Double)call.getMin() * 9.007199254740992E15);
        long maxLong = (long)((Double)call.getMax() * 9.007199254740992E15);
        if (hasLowerBound || hasUpperBound) {
            String ifFalse;
            String ifTrue;
            if (hasLowerBound) {
                boolean lowerOffset = call.isMinStrict() && (minLong & 0x7FFFFFFL) == 0x7FFFFFFL;
                ifTrue = String.format("            builder.withLowerBound(%d, %s(long) (%f * 0x1.0p53)%s >> 27 << 22).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, lowerOffset ? "(" : "", call.getMin(), lowerOffset ? " + 1)" : "", this.latticeIndex);
                boolean upperOffset = call.isMinStrict() || (minLong & 0x7FFFFFFL) != 0L;
                ifFalse = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%s(long) (%f * 0x1.0p53)%s >> 27 << 22) - 1);\n", this.latticeIndex, this.latticeIndex, upperOffset ? "(" : "", call.getMin(), upperOffset ? " + 1)" : "");
            } else {
                boolean upperOffset = !call.isMaxStrict() || (maxLong & 0x7FFFFFFL) != 0L;
                ifTrue = String.format("            builder.withLowerBound(%d, 0).withUpperBound(%d, (%s(long) (%f * 0x1.0p53)%s >> 27 << 22) - 1);\n", this.latticeIndex, this.latticeIndex, upperOffset ? "(" : "", call.getMax(), upperOffset ? " + 1)" : "");
                boolean lowerOffset = !call.isMaxStrict() && (maxLong & 0x7FFFFFFL) == 0x7FFFFFFL;
                ifFalse = String.format("            builder.withLowerBound(%d, %s(long) (%f * 0x1.0p53)%s >> 27 << 22).withUpperBound(%d, (1L << 48) - 1);\n", this.latticeIndex, lowerOffset ? "(" : "", call.getMax(), lowerOffset ? " + 1)" : "", this.latticeIndex);
            }
            this.boundsConfig.append(String.format("        if (%s) {\n", varName));
            this.boundsConfig.append(call.isInverted() ? ifFalse : ifTrue);
            this.boundsConfig.append("        } else {\n");
            this.boundsConfig.append(call.isInverted() ? ifTrue : ifFalse);
            this.boundsConfig.append("        }\n");
        } else {
            this.boundsConfig.append("        if (");
            if (!call.isInverted()) {
                this.boundsConfig.append('!');
            }
            this.boundsConfig.append(varName).append(") {\n");
            this.boundsConfig.append("            return ");
            this.appendClassName(this.boundsConfig, LongStream.class);
            this.boundsConfig.append(".empty();\n");
            this.boundsConfig.append("        }\n");
        }
        ++this.latticeIndex;
    }

    private void longRangeCall(NextLongCall.LongRange call, String varName) {
        throw new IllegalStateException("ClassGenerator does not support unbounded nextLong() ranges");
    }

    private void floatRangedCall(String minVarName, String maxVarName, int nextFloats) {
        this.classBody.append(String.format("     *    float nextFloat%d = rand.nextFloat();\n", nextFloats));
        this.classBody.append(String.format("     *    assert nextFloat%d >= %s && nextFloat%d < %s;\n", nextFloats, minVarName, nextFloats, maxVarName));
        this.parameters.append("float ").append(minVarName).append(", float ").append(maxVarName);
        this.boundsConfig.append(String.format("        if (%s >= %s) {\n", minVarName, maxVarName));
        this.boundsConfig.append("            return ");
        this.appendClassName(this.boundsConfig, LongStream.class);
        this.boundsConfig.append(".empty();\n");
        this.boundsConfig.append("        }\n");
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) (%s * 0x1.0p24f) << 24).withUpperBound(%d, (long) (%s * 0x1.0p24f) << 24);\n", this.latticeIndex, minVarName, this.latticeIndex, maxVarName));
        ++this.latticeIndex;
    }

    private void intRangedCall(NextIntCall.Ranged call, String minVarName, String maxVarName, int nextInts) {
        this.classBody.append(String.format("     *    int nextInt%d = rand.nextInt(%d);\n", nextInts, call.getBound()));
        this.classBody.append(String.format("     *    assert nextInt%d >= %s && nextInt%d < %s;\n", nextInts, minVarName, nextInts, maxVarName));
        this.parameters.append("int ").append(minVarName).append(", int ").append(maxVarName);
        this.boundsConfig.append(String.format("        if (%s >= %s) {\n", minVarName, maxVarName));
        this.boundsConfig.append("            return ");
        this.appendClassName(this.boundsConfig, LongStream.class);
        this.boundsConfig.append(".empty();\n");
        this.boundsConfig.append("        }\n");
        if ((call.getBound() & -call.getBound()) == call.getBound()) {
            int log = Integer.numberOfTrailingZeros(call.getBound());
            this.classBody.append(String.format("        builder.withLowerBound(%d, (long) %s << %d).withUpperBound(%d, ((long) %s << %d) - 1);\n", this.latticeIndex, minVarName, 48 - log, this.latticeIndex, maxVarName, 48 - log));
            ++this.latticeIndex;
        } else {
            long residue = 0x1000000000000L % ((long)call.getBound() << 17);
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, 0).withUpperBound(%d, (1L << 48) - %d);\n", this.latticeIndex, this.latticeIndex, residue));
            ++this.latticeIndex;
            this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) %s << 17).withUpperBound(%d, ((long) %s << 17) - 1);\n", this.latticeIndex, minVarName, this.latticeIndex, maxVarName));
            ++this.latticeIndex;
        }
    }

    private void unboundedIntRangedCall(String minVarName, String maxVarName, int nextInts) {
        this.classBody.append(String.format("     *    int nextInt%d = rand.nextInt();\n", nextInts));
        this.classBody.append(String.format("     *    assert nextInt%d >= %s && nextInt%d < %s;\n", nextInts, minVarName, nextInts, maxVarName));
        this.parameters.append("int ").append(minVarName).append(", int ").append(maxVarName);
        this.boundsConfig.append(String.format("        if (%s >= %s) {\n", minVarName, maxVarName));
        this.boundsConfig.append("            return ");
        this.appendClassName(this.boundsConfig, LongStream.class);
        this.boundsConfig.append(".empty();\n");
        this.boundsConfig.append("        }\n");
        this.classBody.append(String.format("        builder.withLowerBound(%d, (long) %s << 16).withUpperBound(%d, ((long) %s << 16) - 1);\n", this.latticeIndex, minVarName, this.latticeIndex, maxVarName));
        ++this.latticeIndex;
    }

    private void doubleRangedCall(String minVarName, String maxVarName, int nextDoubles) {
        this.classBody.append(String.format("     *    double nextDouble%d = rand.nextDouble();\n", nextDoubles));
        this.classBody.append(String.format("     *    assert nextDouble%d >= %s && nextDouble%d < %s;\n", nextDoubles, minVarName, nextDoubles, maxVarName));
        this.parameters.append("double ").append(minVarName).append(", double ").append(maxVarName);
        this.boundsConfig.append(String.format("        if (%s >= %s) {\n", minVarName, maxVarName));
        this.boundsConfig.append("            return ");
        this.appendClassName(this.boundsConfig, LongStream.class);
        this.boundsConfig.append(".empty();\n");
        this.boundsConfig.append("        }\n");
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, (long) (%s * 0x1.0p53) >> 27 << 22).withUpperBound(%d, (((long) (%s * 0x1.0p53) + 0x7ffffff) >> 27 << 22) - 1);\n", this.latticeIndex, minVarName, this.latticeIndex, maxVarName));
        ++this.latticeIndex;
    }

    private void longRangedCall(String minVarName, String maxVarName, int nextLongs) {
        this.classBody.append(String.format("     *    long nextLong%d = rand.nextLong();\n", nextLongs));
        this.classBody.append(String.format("     *    assert nextLong%d >= %s && nextLong%d < %s;\n", nextLongs, minVarName, nextLongs, maxVarName));
        this.parameters.append("long ").append(minVarName).append(", long ").append(maxVarName);
        String minFirstSeedName = "longMinFirstSeed" + nextLongs;
        this.boundsConfig.append(String.format("        long %s = %s >>> 32 << 16;\n", minFirstSeedName, minVarName));
        this.boundsConfig.append(String.format("        if (%s < 0) {\n", minVarName));
        this.boundsConfig.append(String.format("            %s += (1L << 16);\n", minFirstSeedName));
        this.boundsConfig.append("        }\n");
        String maxFirstSeedName = "longMaxFirstSeed" + nextLongs;
        this.boundsConfig.append(String.format("        long %s = ((%s + 0xffffffffL) >>> 32 << 16) - 1;\n", maxFirstSeedName, maxVarName));
        this.boundsConfig.append(String.format("        if (%s < 0) {\n", maxVarName));
        this.boundsConfig.append(String.format("            %s += (1L << 16);\n", maxFirstSeedName));
        this.boundsConfig.append("        }\n");
        this.boundsConfig.append(String.format("        builder.withLowerBound(%d, %s).withUpperBound(%d, %s);\n", this.latticeIndex, minFirstSeedName, this.latticeIndex, maxFirstSeedName));
        ++this.latticeIndex;
    }

    private void appendClassName(StringBuilder sb, Class<?> clazz) {
        String packageName = clazz.getPackage().getName();
        String canonicalName = clazz.getCanonicalName();
        if (!packageName.equals("java.lang") && !packageName.equals(this.packageName)) {
            Class<?> importedClass = clazz;
            while (importedClass.getDeclaringClass() != null) {
                importedClass = importedClass.getDeclaringClass();
            }
            this.imports.add(importedClass.getCanonicalName());
        }
        sb.append(packageName.isEmpty() ? canonicalName : canonicalName.substring(packageName.length() + 1));
    }
}

